/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include <stdint.h>

#define SRAM_ADDRESS1	0x20000004U

int main(void)
{
	uint32_t value = 0;
	uint32_t volatile *pSramAddr = (uint32_t*)SRAM_ADDRESS1;

	while(1)
	{
		value = *pSramAddr;
		if(value) {
			break;
		}
	}

	for(;;);
}
