/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include <stdint.h>

#define ADC_BASE_ADDR		0x40012000UL

#define ADC_CR1_REG_OFFSET	0x04

#define ADC_CR1_REG_ADDR	(ADC_BASE_ADDR + ADC_CR1_REG_OFFSET)

#define RCC_BASE_ADDR					0x40023800UL

#define RCC_APB2_CLOCK_ENABLE_OFFSET	0x44

#define RCC_APB2_CLOCK_ENABLE_ADDR		(RCC_BASE_ADDR + RCC_APB2_CLOCK_ENABLE_OFFSET)

int main(void)
{
	uint32_t *pRccAddr = (uint32_t *)RCC_APB2_CLOCK_ENABLE_ADDR;

	*pRccAddr |= (1 << 8);

	uint32_t *pAdcAddr = (uint32_t *)ADC_CR1_REG_ADDR;

	*pAdcAddr |= (1 << 8);

	for(;;);
}
