/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include <stdint.h>

#define RCC_BASE_ADDR					0x40023800UL

#define RCC_CLOCK_CONFIG_OFFSET			0x08

#define RCC_CLOCK_CONFIG_ADDR			(RCC_BASE_ADDR + RCC_CLOCK_CONFIG_OFFSET)

#define RCC_AHB1_CLOCK_ENABLE_OFFSET	0x30

#define RCC_AHB1_CLOCK_ENABLE_ADDR		(RCC_BASE_ADDR + RCC_AHB1_CLOCK_ENABLE_OFFSET)

#define GPIOA_BASE_ADDR					0x40020000UL

#define GPIOA_MODE_OFFSET				0x00

#define GPIOA_MODE_ADDR					(GPIOA_BASE_ADDR + GPIOA_MODE_OFFSET)

#define GPIOA_ALT_HIGH_OFFSET			0x24

#define GPIOA_ALT_HIGH_ADDR				(GPIOA_BASE_ADDR + GPIOA_ALT_HIGH_OFFSET)

int main(void)
{
	uint32_t *pRccConfAddr = (uint32_t *)RCC_CLOCK_CONFIG_ADDR;

	*pRccConfAddr &= ~(0x03 << 21);

	uint32_t *pRccAHB1Addr = (uint32_t *)RCC_AHB1_CLOCK_ENABLE_ADDR;

	*pRccAHB1Addr |= (1 << 0);

	uint32_t *pGpioaAddr = (uint32_t *)GPIOA_MODE_ADDR;

	*pGpioaAddr &= ~(0x03 << 16);
	*pGpioaAddr |= (0x02 << 16);


	uint32_t *pGpioAltHighAddr = (uint32_t *)GPIOA_ALT_HIGH_ADDR;
	*pGpioAltHighAddr &= ~(0x0f << 0);

	for(;;);
}
